### ISSUE TITLE
Plot.js nadac2017 line 7

### ISSUE THREAD

**Issue by lorenasandoval88** [KunaalAgarwal/medicaid#5]
I see you are pulling the med names from 2017, but there can be additional names  in other years.  

for getNadacMeds, line 13 , can we do this instead? It uses data from nadac for every third year and only takes a few more seconds. 

async function getNadacMeds(){
    const medList = new Set(getAll_ndcs(nadacDistributions).map(med => med["ndc_description"]));
    return Array.from(medList).sort();
}

**Comment by KunaalAgarwal** [comment]
See commit 0ab3082.
